import Head from "next/head";
import styles from "../../styles/Home.module.css";

import Technologies from "../../views/Technologies";

const technologies = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Technologies />
    </div>
  );
};

export default technologies;
