import "../styles/globals.scss";
import type { AppProps } from "next/app";

import Main from "../layouts/Main/Main";
import Head from "next/head";

import NextNProgress from "nextjs-progressbar";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <NextNProgress height={3} color="#2e377f3d" />

      <Head>
        <title>Tech Hunter</title>
        <meta
          name="google-site-verification"
          content="Jkc-S_EGCFfRdB96Uj2J9YLHOrpGrX6SzDA56usc1Ws"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Component {...pageProps} />
      </Main>
    </>
  );
}
