import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Home from "../views/Home/index";

export default function HomePage() {
  const [showChild, setShowChild] = useState(false);

  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Tech Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
}
