name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_USERNAME}}
        password: ${{ secrets.FTP_PASSWORD}}
